### ISSUE TITLE
System packages for Ubuntu 24.04

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/nextcloud-talk-recording#31]
As mentioned [here](https://github.com/nextcloud/nextcloud-talk-recording/blob/main/docs/building.md#system-packages), the system packages can be built on Ubuntu up to 22.04.

It would be great to have these packages tested and supported also for Ubuntu Server 24.04.

I can try the procedure on Ubuntu Serer 24.04 and report back on any issue, if needed.

**Comment by nickvergessen** [comment]
> I can try the procedure on Ubuntu Serer 24.04 and report back on any issue, if needed.

That would be greatly appreciated.
Most important bit would be if #9 got better or worse

**Comment by pmarini-nc** [comment]
I'll schedule the activity then, and report back.

**Comment by pmarini-nc** [comment]
I'm not using Docker, so I'm getting the instructions from build.sh.

The approach I'm trying is to get the packages built like if I were in Ubuntu Server 22.04, the closest OS among the three currently supported.

But the procedure gets stuck early:

`
python3 -m pip install 'setuptools >= 69.3'
`

throws an error:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

By forcing the installation with the flag `--break-system-packages`, the package got installed but then make fails with:

```
cd build/ubuntu24.04/nextcloud-talk-recording-0.1/ && SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct ../../../../) SETUPTOOLS_USE_DISTUTILS=stdlib python3 setup.py --command-packages=stdeb.command sdist_dsc --with-dh-systemd --debian-version 1~ubuntu24.04 bdist_deb
fatal: not a git repository (or any of the parent directories): .git
/usr/local/lib/python3.12/dist-packages/_distutils_hack/__init__.py:53: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Traceback (most recent call last):
  File "/root/nextcloud-talk-recording-0.1/packaging/build/ubuntu24.04/nextcloud-talk-recording-0.1/setup.py", line 4, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.12/dist-packages/setuptools/__init__.py", line 24, in <module>
    from . import logging, monkey
  File "/usr/local/lib/python3.12/dist-packages/setuptools/logging.py", line 5, in <module>
    from . import monkey
  File "/usr/local/lib/python3.12/dist-packages/setuptools/monkey.py", line 13, in <module>
    import distutils.filelist
ModuleNotFoundError: No module named 'distutils'
```
Curiously enough, just when using the release 0.1 package, I need to replace `$(1)` with `nextcloud_talk_recording` in line 46 of `Makefile`, to avoid a file not found error. But yes, I guess, the main error here is the `No module named 'distutils'`.

Also it is worth mentioning that to get release 0.1 compiled on Ubuntu 22.04 I needed to install setuptools version 68.1.0.

`python3 -m pip install 'setuptools == 68.1.0'`

Please review and let me know

**Comment by AndyScherzinger** [comment]
@pmarini-nc did you try to update the python install command? I had to do a similar thing for the android GH actions at https://github.com/nextcloud/android-config/commit/ce6fbb5a13fec5000cf44d5d913f15937c481e7f because this changed for Ubuntu 22.04...

**Comment by pmarini-nc** [comment]
Hello,
the error `ModuleNotFoundError: No module named 'distutils'` is thrown even if `python3 -m pip install 'setuptools >= 69.3'` is not executed. In any case it seems that python3-setuptools is installed in the stock Ubuntu Server 24.04 distribution.

If we remove the variable `SETUPTOOLS_USE_DISTUTILS=stdlib` from Makefile, we can go past this error but a new error is thrown:

```
Traceback (most recent call last):
  File "/root/nextcloud-talk-recording-0.1/packaging/build/ubuntu24.04/nextcloud-talk-recording-0.1/setup.py", line 6, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/sdist_dsc.py", line 30, in run
    debinfo = self.get_debinfo()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/stdeb/command/common.py", line 189, in get_debinfo
    description = description[:60]
                  ~~~~~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
make: *** [Makefile:89: build/ubuntu24.04/deb/nextcloud-talk-recording_0.1-1~ubuntu24.04_all.deb] Error 1
```
